version: '2'
services:
    jeconomizer-app:
        image: jeconomizer
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://jeconomizer-mariadb:3306/jeconomizer
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jeconomizer-elasticsearch:9300
        ports:
            - 8080:8080
    jeconomizer-mariadb:
        extends:
            file: mariadb.yml
            service: jeconomizer-mariadb
    jeconomizer-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jeconomizer-elasticsearch
